# Generated by Django 4.2 on 2023-04-19 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_in", models.IntegerField(default=0)),
                ("location", models.CharField(max_length=5)),
                ("price", models.IntegerField(null=True)),
                ("date_added", models.DateField(auto_now_add=True, null=True)),
                (
                    "part_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="products.stock"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_paid", models.IntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.salesrecord",
                    ),
                ),
            ],
        ),
    ]
