# Generated by Django 4.2 on 2023-04-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="customer_name",
        ),
        migrations.AddField(
            model_name="cart_id",
            name="customer_name",
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
