# Generated by Django 4.2 on 2023-04-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_cartitem_customer_name_cart_id_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesrecord",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("TF", "Transfer"),
                    ("CS", "Cash"),
                    ("POS", "POS"),
                    ("chq", "Cheque"),
                ],
                max_length=3,
            ),
        ),
    ]
