# Generated by Django 4.2.3 on 2023-07-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_salesrecord_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_id',
            name='is_checked_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart_id',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
