# Generated by Django 4.2.3 on 2023-07-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart_id_is_checked_out_cart_id_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_id',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
